# Generated by Django 4.1.4 on 2022-12-07 17:27

import Company_CRM.core.validators.model_validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Company_CRM.core.validators.model_validators.only_letters_validator])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MaxLengthValidator(2), Company_CRM.core.validators.model_validators.only_letters_validator])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees_photos/', validators=[Company_CRM.core.validators.model_validators.max_file_size_validator_to_5MB])),
                ('position', models.CharField(max_length=50)),
                ('salary', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
