# Generated by Django 4.1.4 on 2022-12-07 18:51

import Company_CRM.core.validators.model_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), Company_CRM.core.validators.model_validators.only_letters_validator]),
        ),
    ]
