# Generated by Django 4.1.4 on 2022-12-07 17:27

import Company_CRM.core.validators.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[Company_CRM.core.validators.model_validators.max_file_size_validator_to_5MB])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
